react-bootstrap/react-overlays

package.json
src/Modal.js
src/Portal.js
src/Position.js
src/RootCloseWrapper.js
src/Transition.js
src/utils/getContainer.js
src/utils/ownerDocument.js
src/utils/ownerWindow.js
test/ModalSpec.js
test/PortalSpec.js
test/PositionSpec.js
test/TransitionSpec.js
test/helpers.js

Original PR: #15 
Moving to react-14 branch to release a prerelease.

Support react v0.14.0

---

src/RootCloseWrapper.js

Needed to merge https://github.com/react-bootstrap/react-bootstrap/pull/1174.

Add back noWrap from React-Bootstrap

---

src/RootCloseWrapper.js
test/RootCloseSpec.js

ran into a need with bootstrap nested dropdowns

Allows nesting root close wrappers

---

src/Affix.js
test/AffixSpec.js

So this doesn't actually fire anything for affixTop is it doesn't change after the first render, not sure if that is ok...

[added] affix state callbacks

---

src/Position.js
test/PositionSpec.js

Closes https://github.com/react-bootstrap/react-bootstrap/issues/1516

Don't forward own props from <Position>

---

src/Modal.js

As discussed here: https://github.com/react-bootstrap/react-bootstrap/pull/1620

Add props to propTypes so they'll be documented.

---

package.json

I can't bump the dev dep yet, as teaspoon doesn't like React 15.

Bump React peer dependency

---

examples/Overlay.js

Should be using a curly apostrophe anyway, so two birds with one stone here.

Fix whack github highlighting

---

package.json

https://github.com/reactjs/prop-types/blob/master/README.md#compatibility
@taion seem ok/right?

Update peers to match reality

---

.travis.yml
src/Modal.js
test/AffixSpec.js
test/ModalSpec.js

Backport modal listener key change

---

test/ModalSpec.js
test/PositionSpec.js

re-enable tests that were disabled for the Portal hotfix

---

src/Modal.js
src/RefHolder.js
test/LegacyPortalSpec.js
test/ModalSpec.js

Oddly, while this fails nearly-consistently locally for me, it apparently almost never fails on Travis.

Fix local test flakiness

---

src/LegacyPortal.js

Fixes #217
Untested (since our tests don't run against React 15).
@bunkscene Do you want to test this locally?

Only call onRendered from LegacyPortal on initial render

---

src/Portal.js
test/LegacyPortalSpec.js
test/PortalSpec.js

Create portal immediately when possible

---

examples/Modal.js
src/Modal.js
src/ModalManager.js
test/ModalManagerSpec.js
test/ModalSpec.js

Modal tweaks again

---

src/Modal.js

Arg I keep not making sure that downstream works with the changes :P
I have now confirmed that this setup plays nicely with RB

Modals again

---

.gitignore
package.json
www/src/components/PropTable.js
www/src/pages/index.js
yarn.lock

maybe we should try this? https://developers.livechatinc.com/blog/how-to-create-javascript-libraries-in-2018-part-2#proxy-directories

old school esm

---

package.json

Allow warning 4.x

---

.travis.yml

I hade no motivation to use nice commit messages. And we squash either.

fix: travis

---

package.json
src/Dropdown.js
www/package.json
www/src/examples/.eslintrc
yarn.lock

- upgraded hooks and uncontrollable with esm support
- removed not used classnames and prop-types-extra

Cleanup package dependencies

---

CHANGELOG.md
src/ModalManager.js
www/src/examples/Modal.js

:blue_heart: Fix typos across **react-overlays repository**
<details><summary>See all fixed files</summary>
<p>
```
react-overlays/CHANGELOG.md:95:20: "depedencies" is a misspelling of "dependencies"
react-overlays/src/ModalManager.js:25:16: "managment" is a misspelling of "management"
react-overlays/www/src/examples/Modal.js:15:17: "psuedo" is a misspelling of "pseudo"
```
</p>
</details>
**FYI:** I used [**Go Spellchecker**](https://github.com/liamzdenek/go-spellcheck) :smile_cat:

Fix typos across react-overlays repository

---

.github/workflows/check-docs.yml
.github/workflows/deploy-docs.yml
README.md

This should allow us to not having to worry about the chore task of building and deploying the docs manually.

ci(actions): add deploy documentation action

---

.github/workflows/test.yml

Should fix some checkout issues
cc @kosmiq

ci: updated checkout plugin

---

src/Modal.tsx

The React types fail on the index signature and props were getting set to any

fix(types): fix Modal prop types

---

src/Modal.tsx

Fixes https://github.com/react-bootstrap/react-overlays/issues/803

fix: Adding missing useEventCallback

---

README.md

docs(readme): fixed broken link to documentation

---

src/Modal.tsx
test/ModalSpec.js

feat(Modal): Prevent onHide when keyboard event defaultPrevented is true

---

package.json

closes https://github.com/react-bootstrap/react-overlays/issues/241

add "sideEffects": false to package.json

---

src/RootCloseWrapper.js

fix: root-close firing immediately in react 17

---

src/Dropdown.tsx
test/DropdownSpec.js

fix: allow internal tabbing in dropdown menu

---

src/Modal.tsx

Part of: https://github.com/react-bootstrap/react-bootstrap/issues/5732
Any changes here will also be applied in https://github.com/react-restart/ui/pull/13

feat: split modal types for ease of export
