examples/Modal.js, src/Modal.js, src/ModalManager.js, src/utils/addFocusListener.js, test/ModalManagerSpec.js, test/ModalSpec.js, test/helpers.js, webpack/test-coverage.config.js, webpack/test.config.js
Abstract out all the container styling and modal jumbling.
This lets us properly support having more then one modal open at at time, by removing all those assumptions.
We still need to think of a proper api to expose to Modal consumers, since they will need to know certain info like the modal's position in the overall stack for styling backdrops correctly. There is a longer term question of allowing a write-access api to the manager if folks want to implement more full blown windows, where they'd need to reorder the stack(s).
__bonus__ we could make this all pluggable so if folks really want to get into it they can just provide their own manager
=> [added] Better Modal state management

package.json, src/Modal.js, test/ModalSpec.js
Not sure about the best way to handle this.
We need to focus _something_ but focusing the wrapping div doesn't work great for bootstrap modals. This method does work, but it opens the possibility of a modal implementer not adding a tab index. The warning feels like a weak attempt to fix that,
Alternatively we could have a `focus` prop or something so the user can focus whatever they want, or just find the first focusable element and use that?
cc: @taion @mfunkie
=> [changed] focus target of the modal to its content

src/AutoAffix.js
This is really just for consistency with what I'm adding in React-Bootstrap. In practice when using `<AutoAffix>`, this just seems like a much saner default.
=> [changed] Friendlier default for AutoAffix

src/Position.js
This should help prevent overflow on some elements while calculating the target's position.
I found this to be useful when using Overlay if the new element forces the browser to display a scrollbar.
Without setting a position static elements shouldn't be affected, but this might cause problems for elements with a relative position.
=> Set default top and left position

src/Overlay.js, src/Position.js, test/PositionSpec.js
This adds the `dynamicPosition` prop to the `Position` component in order to allow for the popover to be repositioned when content changes. It is turned off by default so it should not affect any existing code.
This goes with this issue on react-bootstrap: https://github.com/react-bootstrap/react-bootstrap/issues/1438
=> Add dynamicPosition prop to Position component

src/Position.js, test/PositionSpec.js
Currently, container property of Position component should be mountable, but it can be function, like Portal.js bellow.
https://github.com/react-bootstrap/react-overlays/blob/master/src/Portal.js#L21
=> [WIP]Allow container prop of Position component to be not only mountable but also function

package.json, src/Transition.js, test/TransitionSpec.js
=> [fixed] New props are flushed before any new transition

src/Portal.js, test/PortalSpec.js
Test included, fixes the error `The node to be removed is not a child of this node.` occurring on unmount when the `container` prop was being updated but the `_overlayTarget` was not being moved in the document.
=> Portal container should be updated when container prop changes

src/Portal.js, test/PortalSpec.js
When a portal is mounted and references a container which unmounts before the portal, an error occurs as the result of `getContainerDOMNode` will become "body" and removeChild fails. This removes `getContainerDOMNode` in favor of caching the container on the instance as `_portalContainerNode`.
Test included.
=> Fix unmounting portal when parent is unmounted

src/RootCloseWrapper.js, test/RootCloseSpec.js
Allow the child to remain mounted while conditionally disabling the behavior
=> [added] disabled prop to rootClose

src/RootCloseWrapper.js, test/RootCloseSpec.js
As discussed in #92 
Unlike modal there's no background overlay, so click() is a bit late if the user is doing an interaction that starts onmousedown like dragging or clicking another button.
In order to run the examples from a fresh working tree I had to peg the component-playground version.
I've done some testing of this, I can't find any problems so far. The existing discussions about `mousedown` problems I've found have all been related to Modals and the background overlay.
=> Make <RootCloseWrapper /> hide onmousedown instead of onclick

README.md
The current link just 404s, this just updates it to use the same link that's provided in the description.
=> Update demo link in README

src/RootCloseWrapper.js, src/utils/addEventListener.js
Most likely React unmounted the target in response to some other click.
@jquense This logic is not ideal but probably fine in practice? What do you think?
=> Fix rootClose on unmounting components

src/RootCloseWrapper.js, test/RootCloseWrapperSpec.js
Expose the DOM event through the callback. Allows the callback to determine how the RootCloseWrapper was closed, by `click` or by `keyup` of `esc`.
See #141
=> Resolves #141 Expose DOM event for close events from the RootCloseWrapper.

src/Modal.js
Allow to specify if last focus should be restored after modal is hidden.
I suppose it may be possible and appreciated to write test for it, like those ones https://github.com/react-bootstrap/react-overlays/blob/master/test/ModalSpec.js#L312, but before I spend a lot of time on it, I'd like to be sure you're OK with this change.
The thing is, it's not always desired to call `focus` method on thing that was `activeElement` at the moment modal was shown. I can imagine it's valid in most of use cases, however in some it's not and... I did things I'm really, really ashamed of to workaround this. Please, let my conscience to be cleared.
=> Modal: add restoreFocus option

src/Transition.js, test/TransitionSpec.js
Solves the dang lazy tab loading thing downstream, at least for animation.
also cleans up the logic a bit (I think please double check)
=> add mountOnEnter

examples/App.js, examples/RootCloseWrapper.js, examples/styles.less, src/RootCloseWrapper.js, src/index.js
This PR exposes `<RootCloseWrapper/>` as part of the public API and adds examples. Resolves #77.
Thanks to the maintainers, this package has been super helpful ❤️
=> Expose RootCloseWrapper as part of public API

src/Modal.js
Not sure why this was this way. Now it uses `renderBackdrop` even without a transition
=> Consistently use renderBackdrop

examples/App.js, examples/PropTable.js, package.json, src/Affix.js, src/AutoAffix.js, src/Modal.js, src/Overlay.js, src/Portal.js, src/Position.js, src/RootCloseWrapper.js, src/Transition.js
`React.PropTypes` is deprecated, `prop-types` should be used instead.
https://facebook.github.io/react/blog/2017/04/07/react-v15.5.0.html
https://www.npmjs.com/package/prop-types
=> Use prop-types instead of React.PropTypes

examples/App.js, src/Affix.js, src/Portal.js, src/Position.js, src/RootCloseWrapper.js, src/Transition.js
While upgrading for 15.5 I noticed this package had been recently updated but the latest build was failing.
Fixes duplicate `prop-types` import statements in multiple files.
=> Remove duplicate import statements

examples/Position.js
"an position" should be "a position".
=> Fix a typo on Position demo

src/Modal.js, test/ModalSpec.js
=> Use keyCode instead of key

src/Modal.js, src/RefHolder.js, test/LegacyPortalSpec.js, test/ModalSpec.js
Note base branch.
Mostly fixes https://github.com/react-bootstrap/react-bootstrap/issues/2600
Ref https://github.com/react-bootstrap/react-overlays/pull/208/files#r142582319
Sorry for the random formatting changes on the tests. Got carried away.
Perhaps we should still check for `.hasAttribute` on `dialogElement`, though – in the case where it's e.g. a text node, the dialog element will just be a string and thus won't have that method.
=> Use more robust method of getting dialog element

src/LegacyPortal.js, src/Portal.js, test/LegacyPortalSpec.js, test/PortalSpec.js
It actually doesn't even do anything on the non-legacy portal. Plus it's broken on the legacy portal half the time anyway. Since we already broke it, and we don't document it, I'm going to say this was some internal test-only thing, and it's not semver-breaking to just remove it entirely.
=> Drop busted getOverlayDOMNode

src/Overlay.js, test/OverlaySpec.js
This PR fixes https://github.com/react-bootstrap/react-overlays/issues/153 and supersedes https://github.com/react-bootstrap/react-overlays/pull/156.
=> Adds rootCloseEvent prop to Overlay to pass down to RootCloseWrapper

src/DropdownMenu.js
React 16.6 has a deprecation warning about rendering context directly
Fixes https://github.com/react-bootstrap/react-bootstrap/issues/3347
=> Render context consumer instead of context itself

src/Dropdown.js
On [line 204 in `/src/dropdown.js`](https://github.com/react-bootstrap/react-overlays/blob/master/src/Dropdown.js#L204) you are trying to access `this.menu.contains`. This will throw an error when `this.menu` is not set.
```javascript
if (isInput && (key === ' ' || key !== 'Escape' && _this.menu.contains(target)))
```
---
Logs from my project:
```
Uncaught TypeError: Cannot read property 'contains' of null
at Dropdown._this.handleKeyDown (Dropdown.js:209)
at HTMLUnknownElement.callCallback (react-dom.development.js:147)
at Object.invokeGuardedCallbackDev (react-dom.development.js:196)
at invokeGuardedCallback (react-dom.development.js:250)
at invokeGuardedCallbackAndCatchFirstError (react-dom.development.js:265)
at executeDispatch (react-dom.development.js:571)
at executeDispatchesInOrder …
```
=> Make sure menu ref is set before accessing this.menu.contains

src/Modal.js
This PR will allow the developers to have better control over scroll restoration when using [`react-bootstrap/Modal`](https://github.com/react-bootstrap/react-bootstrap/blob/master/src/Modal.js).
By default, `focus()` will scroll the element into the visible area of the browser window. It can result in unexpected jumps when using [`react-bootstrap/Modal`](https://github.com/react-bootstrap/react-bootstrap/blob/master/src/Modal.js) with `react-router`. Exposing focus options as a prop will allow developers to have control over the [`preventScroll`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/focus#Parameters) parameter.
=> Add restoreFocusOptions prop to Modal

src/utils/manageAriaHidden.js
Fixes #292 
Not sure where to add a test for this within this repo but making this change manually in my local project dependency did get rid of the `aria-hidden="true"` on the root `<div role="dialog" aria-modal="true">` element
=> Fix #292: modal shouldn't make itself aria-hidden

.travis.yml
The problem with broken build are not installed dependencies in www.
As a solution I suggest to run yarn for www after installing
dependencies on CI.
=> Install www dependencies in install hook

.babelrc.js, package.json, yarn.lock
Similar to react-transition-group approach. Also added babel runtime with esm helpers.
Closes https://github.com/react-bootstrap/react-overlays/pull/282
=> Support esm with package.json routers

src/utils/useWaitForDOMRef.js
This was due to `ownerDocument` using `document` when it wasn't
defined (which is the case when building production files).
=> fix(docs): compilation issues when building production files

src/utils/manageAriaHidden.js, test/ModalManagerSpec.js
Fixes the issue raised here: https://github.com/react-bootstrap/react-overlays/issues/240
The modal component contains refs to `dialog` and `backdrop` https://github.com/omniverse/react-overlays/blob/master/src/Modal.js#L309-L315
not `root` and `backdrop` as destructured in manageAriaHidden https://github.com/omniverse/react-overlays/blob/master/src/Modal.js#L309-L315
So the aria-hidden="true" attribute was getting applied to the dialog itself and breaking screen readers, accessibility features, etc.
=> Mismatch between Modal.dialog and hideSiblings parameters

.github/workflows/test.yml
Currently, the build is only being triggered whenever there is
a push to the repository.
This does not lead to a build being triggered whenever there is a
push to a branch on a forked repo.
This fix allows it to trigger on every push *or* every pull
request.
We'll probably need to also fix the configuration on the
React-Bootstrap repo.
=> ci(actions): fix for build not triggering on forked pull request

package.json, src/Dropdown.js, src/Modal.js, src/ModalManager.js, src/useRootClose.js, src/utils/isOverflowing.js, test/ModalManagerSpec.js, www/src/components/Playground.js, www/yarn.lock, yarn.lock
Ref https://github.com/react-bootstrap/dom-helpers/commit/87e2fe448b5e852574e1ee63bd3f2102b4c65d79
/cc @jquense
=> Upgrade dom-helpers

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md
Essentially just a copy/paste of the issue templates from the React Bootstrap repo.
=> feat(github): add issue templates

src/Portal.js
#597 missed this lifecycle method.
=> fix(0.x): missed UNSAFE lifecycle in Portal (React 17)

src/DropdownMenu.tsx, src/Overlay.tsx, src/mergeOptionsWithPopperConfig.ts, src/usePopper.ts, test/usePopperSpec.js, www/src/examples/Dropdown.mdx, www/src/examples/Overlay.mdx
Should be fine to adapt in RB without a breaking change there
BREAKING CHANGE: popperConfig longer accept object forms of modifiers, pass an array instead
BREAKING CHANGE: overlay and dropdown menu injected values are different
BREAKING CHANGE: overlay no longer triggers an update when placement change due to auto or flip placements
=> feat: improve popper integration

src/manageAriaHidden.ts
I think the name show is misleading as show = true will hide the node from screen readers.
=> Rename parameter of ariaHidden(): show -> hide

src/ModalManager.js, test/ModalManagerSpec.js
Fixes a couple modal accessibility issues in the 0.9 branch for react-bootstrap 0.33:
* https://github.com/react-bootstrap/react-bootstrap/issues/4790: active modals have `aria-hidden="true"` (regression introduced when react-bootstrap 0.33 upgraded to react-overlays 0.9)
* https://github.com/react-bootstrap/react-overlays/issues/240: closing a modal when multiple modals are open doesn't remove `aria-hidden="true"` from the next top modal (old issue, but still present in react-bootstrap 0.33)
=> [BS3] Modal accessibility fixes

src/usePopper.ts, test/usePopperSpec.js
Fixes https://github.com/react-bootstrap/react-bootstrap/issues/5488
If id already exists in `aria-describedby`, ignore it.
=> fix(Popper): Prevent duplicate ids in aria-describedby

.github/workflows/ci.yml
Fixes the following error
> Error: Calling brew cask install is disabled! Use brew install [--cask] instead.
=> chore(ci): Fix brew cask install

src/Dropdown.tsx
Resolves: https://github.com/react-bootstrap/react-bootstrap/issues/5883
Tested using next.js in development mode. (Fun fact: i've been able to reproduce this bug only using next js and only in dev mode - in production everything worked fine)
=> fix(Dropdown): add checking if ref exists on dropdown

src/Dropdown.tsx, test/DropdownSpec.js
Avoids calling `onToggle(false)` when "tab" is pressed and the dropdown is closed
=> fix(Dropdown): avoid calling onToggle when tabbing if menu ref not set

src/useRootClose.ts, test/useRootCloseSpec.js
`useRootClose` should inspect `Event.composedPath()` so that it can react correctly to events coming from an open shadow root.
In order to test this, it was also necessary to add a workaround for simulant which is creating events with `composed: false` by default.
=> Support useRootClose inside open shadow roots

package.json, src/usePopper.ts, yarn.lock
As per title, fixes: https://github.com/react-bootstrap/react-overlays/issues/1012
=> fix(usePopper): fix exported Modifier type
